"""
Django settings for bk_habitto project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
# --- CONFIGURACIÓN GDAL PARA WINDOWS (SOLUCIONA EL ERROR ImproperlyConfigured) ---
import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

if os.name == 'nt':
    # Detección robusta de librerías GIS en Windows
    VENV_PATH = BASE_DIR / 'venv'
    OSV_OSGEO_DIR = VENV_PATH / 'Lib' / 'site-packages' / 'osgeo'

    def _first_existing(paths):
        for p in paths:
            if p and os.path.exists(str(p)):
                return str(p)
        return None

    # Candidatos de directorios que contienen DLLs
    dll_dirs = [
        OSV_OSGEO_DIR,
        Path('C:/OSGeo4W/bin'),
        Path('C:/Program Files/OSGeo4W/bin'),
        Path('C:/Program Files/GDAL'),
        Path('C:/OSGeo4W'),
    ]
    dll_dir = _first_existing(dll_dirs)

    # Añadir directorio a la búsqueda de DLLs (Windows 10+)
    try:
        if dll_dir:
            os.add_dll_directory(dll_dir)
    except Exception:
        pass

    # Candidatos de nombres de DLL GDAL/GEOS
    gdal_candidates = [
        OSV_OSGEO_DIR / 'gdal.dll',
        OSV_OSGEO_DIR / 'gdal304.dll',
        OSV_OSGEO_DIR / 'gdal302.dll',
        Path(dll_dir) / 'gdal.dll' if dll_dir else None,
        Path(dll_dir) / 'gdal304.dll' if dll_dir else None,
    ]
    geos_candidates = [
        OSV_OSGEO_DIR / 'geos_c.dll',
        Path(dll_dir) / 'geos_c.dll' if dll_dir else None,
    ]
    proj_candidates = [
        Path('C:/OSGeo4W/share/proj'),
        Path('C:/OSGeo4W/apps/proj/share'),
        OSV_OSGEO_DIR / 'data',
    ]

    gdal_path = _first_existing(gdal_candidates)
    geos_path = _first_existing(geos_candidates)
    proj_path = _first_existing(proj_candidates)

    # Definir ajustes de Django para GDAL/GEOS
    if gdal_path:
        GDAL_LIBRARY_PATH = gdal_path
        os.environ['GDAL_LIBRARY_PATH'] = gdal_path  # por si alguna lib lo consulta desde env
    if geos_path:
        GEOS_LIBRARY_PATH = geos_path
        os.environ['GEOS_LIBRARY_PATH'] = geos_path
    if proj_path:
        os.environ['PROJ_LIB'] = proj_path

# --- CONFIGURACIÓN GDAL PARA LINUX/NIXPACKS (RAILWAY) ---
else:
    if not os.environ.get('GDAL_LIBRARY_PATH'):
        import glob
        libs = glob.glob('/nix/store/*-gdal-*/lib/libgdal.so*')
        if libs:
            libs.sort(key=len)
            os.environ['GDAL_LIBRARY_PATH'] = libs[0]
            GDAL_LIBRARY_PATH = libs[0]

    if not os.environ.get('GEOS_LIBRARY_PATH'):
        import glob
        libs = glob.glob('/nix/store/*-geos-*/lib/libgeos_c.so*')
        if libs:
            libs.sort(key=len)
            os.environ['GEOS_LIBRARY_PATH'] = libs[0]
            GEOS_LIBRARY_PATH = libs[0]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-3kqk+6%34%qg8==fc$!#^-z76^eic84q0$o_%-an0cfea%7$b8')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',  # Soporte GIS para PostGIS
    'channels',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_gis',  # Soporte GeoJSON para REST Framework
    'rest_framework_simplejwt',
    'django_filters',
    'habittoapp',
    'user',
    'property',
    'zone',  # Nueva app para zonas
    'amenity',
    'photo',
    'review',
    'payment',
    'paymentmethod',
    'notification',
    'message',
    'incentive',
    'guarantee',
    'matching',
    'report',
    'payments',
    'django.contrib.sites',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.apple',
    'django_extensions',
]

# Eliminar esta línea: AUTH_USER_MODEL = 'user.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'bk_habitto.middleware.APILoggingMiddleware',  # Middleware personalizado para logging de API
]

ROOT_URLCONF = 'bk_habitto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bk_habitto.wsgi.application'
ASGI_APPLICATION = 'bk_habitto.asgi.application'

# Hosts para despliegue
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL', 'postgis://postgres:sistemas123@localhost:5432/habito_db'),
        conn_max_age=600,
        ssl_require=False
    )
}
DATABASES['default']['ENGINE'] = 'django.contrib.gis.db.backends.postgis'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': (
        'bk_habitto.renderers.WrappedJSONRenderer',
    ),
    'EXCEPTION_HANDLER': 'bk_habitto.exceptions.wrapped_exception_handler',
}

# Simple JWT configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# Allauth / dj-rest-auth configuration
SITE_ID = int(os.environ.get('SITE_ID', '1'))
ACCOUNT_EMAIL_VERIFICATION = os.environ.get('ACCOUNT_EMAIL_VERIFICATION', 'optional')
ACCOUNT_AUTHENTICATION_METHOD = 'username'
ACCOUNT_EMAIL_REQUIRED = False
SOCIALACCOUNT_ADAPTER = 'bk_habitto.social_adapter.CustomSocialAccountAdapter'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

REST_USE_JWT = True
JWT_AUTH_COOKIE = os.environ.get('JWT_AUTH_COOKIE', None)
DJ_REST_AUTH = {
    'TOKEN_MODEL': None,
}

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.environ.get('GOOGLE_CLIENT_ID', ''),
            'secret': os.environ.get('GOOGLE_CLIENT_SECRET', ''),
            'key': ''
        },
        'SCOPE': ['email', 'profile'],
        'AUTH_PARAMS': {'access_type': 'offline'}
    },
    'facebook': {
        'APP': {
            'client_id': os.environ.get('FACEBOOK_APP_ID', ''),
            'secret': os.environ.get('FACEBOOK_APP_SECRET', ''),
            'key': ''
        },
        'SCOPE': ['email', 'public_profile'],
        'AUTH_PARAMS': {'auth_type': 'rerequest'}
    },
    'apple': {
        'APP': {
            'client_id': os.environ.get('APPLE_CLIENT_ID', ''),
            'secret': os.environ.get('APPLE_CLIENT_SECRET', ''),
            'key': ''
        },
        'SCOPE': ['email', 'name']
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

CORS_ALLOW_ALL_ORIGINS = True
CSRF_TRUSTED_ORIGINS = ['https://*.railway.app', 'http://localhost:3000']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Configuración de Logging para API
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'api': {
            'format': '{asctime} - {levelname} - {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'api',
        },
        'api_file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'api.log',
            'formatter': 'api',
        },
    },
    'loggers': {
        'api_logger': {
            'handlers': ['console', 'api_file'] if DEBUG else [],
            'level': 'INFO' if DEBUG else 'ERROR',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}

# Configuración de Celery
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/La_Paz'
CELERY_ENABLE_UTC = True

# Configuración de Redis para caché (opcional)
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}
# Channels / WebSockets
redis_layer_url = os.environ.get('CHANNEL_REDIS_URL', os.environ.get('REDIS_URL'))
if redis_layer_url:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [redis_layer_url]
            }
        }
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer'
        }
    }

MATCH_MIN_SCORE = int(os.environ.get('MATCH_MIN_SCORE', '0'))

# Configuración de Pagos BNB QR
BNB_QR = {
    'BASE_URL': os.environ.get('BNB_QR_URL', 'http://test.bnb.com.bo/'),
    'ACCOUNT_ID': os.environ.get('BNB_QR_ACCOUNT_ID', 's9CG8FE7Id75ef2jeX9bUA=='),
    'INITIAL_AUTH_ID': os.environ.get('BNB_QR_INITIAL_AUTH_ID', '713K7PvTlACs1gdmv9jGgA=='),
    'CURRENT_AUTH_ID': os.environ.get('BNB_QR_CURRENT_AUTH_ID', 'TuClaveSegura15*'),
    'DESTINATION_ACCOUNT_ID': os.environ.get('BNB_QR_DESTINATION_ACCOUNT_ID', '1'),
}
