# Generated by Django 5.2.7 on 2025-10-24 19:24

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la zona (ej: Centro, Equipetrol, Norte)', max_length=100, unique=True)),
                ('bounds', django.contrib.gis.db.models.fields.PolygonField(help_text='Límites geográficos de la zona en formato GeoJSON', srid=4326)),
                ('description', models.TextField(blank=True, help_text='Descripción opcional de la zona', null=True)),
                ('avg_price', models.DecimalField(decimal_places=2, default=0, help_text='Precio promedio de propiedades activas en la zona', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('offer_count', models.IntegerField(default=0, help_text='Número de propiedades activas en la zona', validators=[django.core.validators.MinValueValidator(0)])),
                ('demand_count', models.IntegerField(default=0, help_text='Número de búsquedas/favoritos en la zona', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ZoneSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_params', models.JSONField(default=dict, help_text='Parámetros de búsqueda utilizados')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que realizó la búsqueda (opcional para búsquedas anónimas)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_logs', to='zone.zone')),
            ],
            options={
                'verbose_name': 'Log de Búsqueda por Zona',
                'verbose_name_plural': 'Logs de Búsquedas por Zona',
                'ordering': ['-timestamp'],
            },
        ),
    ]
