# Generated by Django 5.2.7 on 2025-11-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0002_initial_zones_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='match_activity_score',
            field=models.FloatField(default=0.0, help_text='Actividad de matches en la zona'),
        ),
    ]
