# Generated by Django 5.2.7 on 2025-12-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportattachment',
            name='file',
        ),
        migrations.AddField(
            model_name='reportattachment',
            name='file_url',
            field=models.URLField(default='https://res.cloudinary.com/dpdpgl5kg/image/upload/f_auto,q_auto/v1/habitto/properties/umyw1jlhzqhe3rjhr7ar', max_length=500),
            preserve_default=False,
        ),
    ]
