# Generated by Django 5.2.7 on 2025-10-24 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0001_initial'),
        ('zone', '0002_initial_zones_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncentiveRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('incentive_type', models.CharField(choices=[('high_demand', 'Alta Demanda'), ('low_supply', 'Baja Oferta'), ('market_balance', 'Balance de Mercado'), ('zone_promotion', 'Promoción de Zona')], max_length=20)),
                ('min_demand_count', models.IntegerField(default=0)),
                ('max_offer_count', models.IntegerField(default=999999)),
                ('min_offer_demand_ratio', models.FloatField(default=0.0)),
                ('max_offer_demand_ratio', models.FloatField(default=999.0)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_multiplier', models.FloatField(default=1.0, help_text='Multiplicador basado en la intensidad de la condición')),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.IntegerField(default=30, help_text='Duración del incentivo en días')),
                ('cooldown_days', models.IntegerField(default=7, help_text='Días de espera antes de generar otro incentivo similar')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='incentive',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='incentive',
            name='incentive_type',
            field=models.CharField(choices=[('high_demand', 'Alta Demanda'), ('low_supply', 'Baja Oferta'), ('market_balance', 'Balance de Mercado'), ('zone_promotion', 'Promoción de Zona')], default='market_balance', max_length=20),
        ),
        migrations.AddField(
            model_name='incentive',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='incentive',
            name='offer_demand_ratio',
            field=models.FloatField(blank=True, help_text='Ratio oferta/demanda al momento de crear el incentivo', null=True),
        ),
        migrations.AddField(
            model_name='incentive',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='incentive',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incentive',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incentives', to='zone.zone'),
        ),
        migrations.AddField(
            model_name='incentive',
            name='zone_activity_score',
            field=models.FloatField(blank=True, help_text='Puntuación de actividad de la zona', null=True),
        ),
        migrations.AddIndex(
            model_name='incentive',
            index=models.Index(fields=['zone', 'incentive_type'], name='incentive_i_zone_id_82fcc4_idx'),
        ),
        migrations.AddIndex(
            model_name='incentive',
            index=models.Index(fields=['user', 'is_active'], name='incentive_i_user_id_bf3426_idx'),
        ),
        migrations.AddIndex(
            model_name='incentive',
            index=models.Index(fields=['created_at'], name='incentive_i_created_bc6ab8_idx'),
        ),
    ]
