# Generated by Django 5.2.7 on 2025-11-05 15:38

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amenity', '0001_initial'),
        ('zone', '0003_zone_match_activity_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('property', 'Property'), ('roommate', 'Roommate'), ('agent', 'Agent')], max_length=20)),
                ('subject_id', models.IntegerField(help_text='ID de Property, RoommateRequest o Agent (User)')),
                ('score', models.FloatField()),
                ('metadata', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('neutral', 'Neutral')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='matching.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('budget_min', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('budget_max', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('desired_types', models.JSONField(default=list)),
                ('bedrooms_min', models.IntegerField(blank=True, null=True)),
                ('bedrooms_max', models.IntegerField(blank=True, null=True)),
                ('pet_allowed', models.BooleanField(default=False)),
                ('wfh_preference', models.BooleanField(default=False)),
                ('roommate_preference', models.CharField(choices=[('no', 'No'), ('looking', 'Buscando'), ('open', 'Abierto')], default='no', max_length=20)),
                ('roommate_preferences', models.JSONField(default=dict)),
                ('vibes', models.JSONField(default=list)),
                ('semantic_embedding', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, to='amenity.amenity')),
                ('preferred_zones', models.ManyToManyField(blank=True, to='zone.zone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoommateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_move_in_date', models.DateField(blank=True, null=True)),
                ('max_roommates', models.IntegerField(default=2)),
                ('gender_preference', models.CharField(choices=[('male', 'Hombres'), ('female', 'Mujeres'), ('any', 'Cualquiera')], default='any', max_length=20)),
                ('smoker_ok', models.BooleanField(default=False)),
                ('budget_per_person', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_requests', to='matching.searchprofile')),
            ],
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['match_type', 'target_user'], name='matching_ma_match_t_ba36f4_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['match_type', 'subject_id'], name='matching_ma_match_t_71aa55_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status'], name='matching_ma_status_8042fa_idx'),
        ),
    ]
