# Generated by Django 5.2.7 on 2025-11-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='children_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='commute_distance_km',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='education_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='family_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Hombre'), ('female', 'Mujer'), ('other', 'Otro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='has_vehicle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='languages',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='lifestyle',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='pets_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='schedule',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='smoker',
            field=models.BooleanField(default=False),
        ),
    ]
