# Generated by Django 5.2.7 on 2025-11-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_searchprofile_age_searchprofile_children_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchprofile',
            name='stable_job',
            field=models.BooleanField(default=False),
        ),
    ]