# Generated by Django 5.2.7 on 2025-10-24 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_add_profile_picture_history'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='profilepicturehistory',
            name='user_profile_current_idx',
        ),
    ]
