# Generated by Django 5.2.7 on 2025-11-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_profilepicturehistory_user_profile_current_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='agent_commission_rate',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roommate_vibes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
