# Generated by Django 5.2.7 on 2025-11-28 16:00

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userprofile_verification_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id_card_back',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.verification_document_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id_card_front',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.verification_document_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.verification_document_path),
        ),
    ]
