# Generated by Django 5.2.7 on 2025-11-28 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_block'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='block',
            new_name='user_block_blocker_24f410_idx',
            old_name='user_blocker_blocked_idx',
        ),
    ]
