# Generated by Django 6.0 on 2025-12-09 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_userlocationpoint'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userlocationpoint',
            new_name='user_userlo_user_id_30d3a8_idx',
            old_name='user_loc_user_created_idx',
        ),
    ]
