# Generated by Django 5.2.7 on 2025-12-16 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_add_cloudinary_urls'),
        ('user', '0012_rename_user_loc_user_created_idx_user_userlo_user_id_30d3a8_idx'),
    ]

    operations = [
    ]
