# Generated by Django 5.2.7 on 2025-12-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_merge_20251216_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepicturehistory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='id_card_back',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='id_card_front',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='selfie',
        ),
    ]
