# Generated by Django 5.2.7 on 2026-01-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_profilepicturehistory_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='video_presentation_url',
            field=models.URLField(blank=True, help_text='URL del video de presentación (corto)', max_length=500, null=True),
        ),
    ]
