# Generated by Django 5.2.7 on 2025-10-24 19:24

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Ubicación geográfica de la propiedad', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='property',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Zona geográfica donde se encuentra la propiedad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='zone.zone'),
        ),
    ]
