# Generated by Django 5.2.7 on 2025-10-26 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_location_property_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='longitude',
        ),
    ]
