# Generated by Django 5.2.7 on 2025-11-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_allows_roommates_property_is_furnished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='preferred_tenant_gender',
            field=models.CharField(choices=[('any', 'Cualquiera'), ('male', 'Hombres'), ('female', 'Mujeres')], default='any', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='children_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='pets_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='smokers_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='students_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='stable_job_required',
            field=models.BooleanField(default=False),
        ),
    ]