# Generated by Django 5.2.7 on 2025-11-20 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_searchprofile_stable_job'),
        ('property', '0006_propertyviewevent_propertyview'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_roomie_listing',
            field=models.BooleanField(default=False, help_text='Indica si esta propiedad es una publicación de búsqueda de roomie'),
        ),
        migrations.AddField(
            model_name='property',
            name='roomie_profile',
            field=models.ForeignKey(blank=True, help_text='Perfil del inquilino que busca roomie', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roomie_properties', to='matching.searchprofile'),
        ),
    ]
