# Generated by Django 5.2.7 on 2025-11-29 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_property_is_available_propertyoccupancy'),
        ('property', '0008_propertyinteractionevent'),
    ]

    operations = [
    ]
