# Generated by Django 5.2.7 on 2025-12-16 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_add_cloudinary_urls'),
        ('property', '0009_merge_20251129_1434'),
    ]

    operations = [
    ]
