# Generated by Django 5.2.7 on 2025-12-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_merge_20251216_1913'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='propertyinteractionevent',
            new_name='property_pr_user_id_4f055c_idx',
            old_name='prop_inter_user_event_idx',
        ),
    ]
