# Generated by Django 5.2.7 on 2026-01-14 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_rename_prop_inter_user_event_idx_property_pr_user_id_4f055c_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='parent_property',
            field=models.ForeignKey(blank=True, help_text='Propiedad padre a la que pertenece esta unidad (ej: Edificio para un Depto)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='property.property'),
        ),
        migrations.AddField(
            model_name='property',
            name='unit_number',
            field=models.CharField(blank=True, help_text='Número o identificador de la unidad (ej: 2B, 101)', max_length=50, null=True),
        ),
    ]
