# Generated by Django 5.2.7 on 2026-01-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_property_parent_property_property_unit_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='videos_urls',
            field=models.JSONField(blank=True, default=list, help_text='Lista de URLs de videos'),
        ),
    ]
