# Generated by Django 5.2.7 on 2025-12-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_add_cloudinary_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
    ]
